name: Build Qt Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qt-version: [6.2.0] # Change to your desired Qt version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update -qq
            sudo apt-get install -y qt${{ matrix.qt-version }}-desktop-dev
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install qt-creator
            choco install qt${{ matrix.qt-version }}-msvc2019
          fi

      - name: Build Qt Application
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mkdir build
            cd build
            qmake ..
            make
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            mkdir build
            cd build
            qmake ..
            nmake
          fi

      - name: Create Release
        uses: softprops/gotta-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          title: "Qt Application Build"
          body: "Automated build of Qt application"
          artifact: build
